var CONFIG = {

  TILE: 40,
  ROWS: 10,
  PIECE_COLS: 8,

  CANVAS_W: 800,
  CANVAS_H: 400,

  MOVE_SPEED: 5,
  GRAVITY: .4,
  JUMP_POWER: 15,
  MAX_FALL: 12,
  MAX_JUMPS: 2,

  PLAYER_SIZE: 32,
  PLAYER_RADIUS: 16,

  LINE_WIDTH: 3,
  DOT_DISTANCE: 0.55,

  // The wall stays threatening without catching the player too quickly.
  SPIKE_WALL_WIDTH: 48,
  SPIKE_WALL_SPEED: 2.4,

  INVADER_ROWS: 2,
  INVADERS_PER_ROW: 4,
  INVADER_SHOT_INTERVAL: 95,
  INVADER_SHOT_SPEED: 3.5,
  INVADER_SPEED: 0.45,
  INVADER_SIZE: 24,

  START_LEVEL: 0
};
